doctrine_migrations:
    storage:
        table_storage:
            table_name: sylius_migrations
    migrations_paths:
        'App\Offer\Infrastructure\Doctrine\Migrations': "%kernel.project_dir%/src/Offer/Infrastructure/Doctrine/Migrations"
