parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8mb4

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true
                mappings:
#                    ProductDomain:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Offer/Domain'
#                        prefix: 'App\Product\Domain'
#                        alias: ProductDomain
#                    SyliusProductClothes:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Offer/Infrastructure/Sylius/Clothes/Entity'
#                        prefix: 'App\Product\Infrastructure\Sylius\Clothes\Entity'
#                        alias: SyliusProductClothes
